### PR TITLE
Adds split_set to datasets. Closes issue #57

### PR DESCRIPTION
**Pull request by seba-1511**
This PR adds a split_set method to the Dataset class. It allows to take a given amount of a set and transfer it to a new dataset. Particularly useful when used with spearmint to create a validation set. Some considerations:

* I wasn't sure about how to correctly get a random number, with regards to efficiency and respect to the random seed. (neon/dataset.py, line 264) The way I did it somehow feels wrong to me.
* I am testing this functionality in test_cifar100.py, as I need to instantiate a dataset. I also tested its call in the fit function with yaml files on my machine.
* It works batchwise, as this is called after dataset.format(). I think that changing it to work in load() would take a lot more changes, and is not worth the added complexity.

As mentioned in #56, I also think that having a way to have validation scores while training can be very useful. (This early stopping will help save a lot of time with spearmint) Do you want me to work on that and add it to model ? (ie, something like if print_validation then do it) Or is that a functionality you prefer to keep out of the framework ?

Thanks for your comments,
Séb

### CODE REVIEW

**Comment by scttl** [comment]
Hi Séb,

Thanks for taking the effort to implement this pull request, but I don't think we can accept it as-is unfortunately.  

See my comments in #57 for additional detail, but we really don't want to be shuttling data around between train and validation sets after they have already been loaded and are sitting on device.  We currently have the ability to do this as part of the `load()` process for directories of images using the `BatchWriter` class and the `validation_pct` parameter.  What would be really useful for us is enabling this functionality at load time for non `BatchWriter` based datasets.  If that's something you could implement we'd be more than happy to take a look!

As for the validation scores while training, we're probably going to end up supporting functionality like this through asynchronous callbacks that users can specify to run at the end of each epoch, but we're still trying to determine exactly how that will look.  If you want to implement the `print_validation` (default to False) approach I think that would still have some use in the interim, so again we'd be happy to take a look at a pull request for that.

**Comment by seba-1511** [comment]
Hello,

Alright, I'll move the validation_split in the init() of the non BatchWriter datasets (and will rename it to validation_pct for consistency). I thought about the shuttling problem, but I assumed that it would only be the reference to memory that would be passed around. Is my assumption wrong, or is that kind of behavior outside of load that is problematic ? In the latter case, (and if having the batch approximation is not a problem) could we simply call the current split_set after format ? Otherwise, I'll work with the data before it is formatted.

I can also do the print_validation approach, directly in the models. Is that fine if they both come in the same pull request ?

Have a nice weekend,
Séb

**Comment by scttl** [comment]
Hi Séb,

The `dataset.format()` function that most datasets call at the end of the `load()` will actually copy the first batch of values from host and onto the device (ex. GPU memory for a GPU backend), so that's why we need to implement these changes prior to that.  

I think you can adapt your `split_set` code to 1) have it be called before `format()`, 2) not use `backend` calls for your random sampling -- numpy should be ok since the data should be on host at that stage, 3) not take any parameters except for maybe `to_set` and `from_set` (everything else should be part of the `Dataset` class).  I think doing something fairly similar to `sample_training_data` could work (for smaller datasets at least).  Another minor gripe would be to utilize one of the synthetic datasets like UniformRandom or ToyImages for your testing (neither has validation out of the box so should be useful).  That way you would need to download CIFAR100 to run the tests -- I'd also rename the file to something like `test_val_split.py` instead of `test_cifar100.py`.

I'd put the `print_validation` stuff in a separate pull request if possible (easier to track independently).

**Comment by seba-1511** [comment]
Thanks, just implemented that in #60

**Pull request closed without merging**
